// SPDX-FileCopyrightText: (C) 2025 Jason Ish <jason@codemonkey.net>
// SPDX-License-Identifier: MIT

use std::path::Path;

// No prelude as this is exported in the library and the prelude isn't
// for now.
use anyhow::Result;
use tracing::info;

pub const AF_PACKET_STUB: &str = "
%YAML 1.1
---

# Do not edit, automatically generated on every restart.

af-packet:
  - interface: default
    threads: auto
    cluster-id: 131
    tpacket-v3: yes
";

const EVEBOX_SERVER_SOCKET_CONFIG: &str = "# Generated by evectl. Do not edit.
input:
  enabled: true
  sockets:
    - path: /var/run/suricata/eve.sock
      type: unix_stream
      mode: \"0660\"
";

const EVEBOX_AGENT_SOCKET_CONFIG: &str = "# Generated by evectl. Do not edit.
input:
  sockets:
    - path: /var/run/suricata/eve.sock
      type: unix_stream
      mode: \"0660\"
";

// The plain eve.json path picks up any leftover file from before the
// move to timestamped spool files.
const EVEBOX_SERVER_FILE_CONFIG: &str = "# Generated by evectl. Do not edit.
input:
  enabled: true
  paths:
    - \"/var/log/suricata/eve.json\"
    - \"/var/log/suricata/eve.json.[0-9]*\"
  delete-spool-files: true
";

// The agent needs a data-directory for bookmarks, which spool file
// deletion requires.
const EVEBOX_AGENT_FILE_CONFIG: &str = "# Generated by evectl. Do not edit.
data-directory: /var/lib/evebox
input:
  paths:
    - \"/var/log/suricata/eve.json\"
    - \"/var/log/suricata/eve.json.[0-9]*\"
  delete-spool-files: true
";

pub fn write_af_packet_stub(path: &Path) -> Result<()> {
    info!("Writing af-packet partial to {}", path.display());
    std::fs::write(path, AF_PACKET_STUB)?;
    Ok(())
}

pub fn write_evebox_server_socket_config(path: &Path) -> Result<()> {
    write_evebox_config(path, EVEBOX_SERVER_SOCKET_CONFIG)
}

pub fn write_evebox_agent_socket_config(path: &Path) -> Result<()> {
    write_evebox_config(path, EVEBOX_AGENT_SOCKET_CONFIG)
}

pub fn write_evebox_server_file_config(path: &Path) -> Result<()> {
    write_evebox_config(path, EVEBOX_SERVER_FILE_CONFIG)
}

pub fn write_evebox_agent_file_config(path: &Path) -> Result<()> {
    write_evebox_config(path, EVEBOX_AGENT_FILE_CONFIG)
}

fn write_evebox_config(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_server_and_agent_socket_configs() {
        let dir = tempfile::tempdir().unwrap();
        let server = dir.path().join("server").join("evectl-input.yaml");
        let agent = dir.path().join("agent").join("evectl-input.yaml");

        write_evebox_server_socket_config(&server).unwrap();
        write_evebox_agent_socket_config(&agent).unwrap();

        let server = std::fs::read_to_string(server).unwrap();
        assert!(server.contains("enabled: true"));
        assert!(server.contains("type: unix_stream"));
        assert!(server.contains("mode: \"0660\""));

        let agent = std::fs::read_to_string(agent).unwrap();
        assert!(!agent.contains("enabled: true"));
        assert!(agent.contains("path: /var/run/suricata/eve.sock"));
    }

    #[test]
    fn writes_server_and_agent_file_configs() {
        let dir = tempfile::tempdir().unwrap();
        let server = dir.path().join("server").join("evectl-input.yaml");
        let agent = dir.path().join("agent").join("evectl-input.yaml");

        write_evebox_server_file_config(&server).unwrap();
        write_evebox_agent_file_config(&agent).unwrap();

        let server = std::fs::read_to_string(server).unwrap();
        assert!(server.contains("enabled: true"));
        assert!(server.contains("\"/var/log/suricata/eve.json.[0-9]*\""));
        assert!(server.contains("delete-spool-files: true"));
        assert!(!server.contains("data-directory"));

        let agent = std::fs::read_to_string(agent).unwrap();
        assert!(agent.contains("data-directory: /var/lib/evebox"));
        assert!(agent.contains("\"/var/log/suricata/eve.json.[0-9]*\""));
        assert!(agent.contains("delete-spool-files: true"));
    }
}
