name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-gnu
    steps:
      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
      - run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - run: |
          echo "$HOME/.cargo/bin"
          ls "$HOME/.cargo/bin"
      - run: |
          curl -OL https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz
          tar xvf cross-x86_64-unknown-linux-musl.tar.gz
          mv cross $HOME/.cargo/bin
      - uses: actions/checkout@v4
      - run: cross build --target ${{ matrix.target }}
